version: "3.2"



services:
  proxy:
    image: dperson/torproxy
    ports:
      - 8118:8118
      - 9050:9050
    networks:
      - tor_network
    deploy:
      replicas: 10
      placement:
        constraints: [ node.role == manager ]

  node_ok:
    image: node_ok:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - tor_network
    deploy:
      replicas: 1
      placement:
        constraints: [ node.role == manager ]


networks:
  tor_network:
    driver: overlay
    attachable: true
